#!/usr/bin/env perl

use warnings;
use strict;

use DBIx::Class2::_Util; # load early in case any shims are needed

my $lib_dir = 'lib';
my $pod_dir = 'maint/.Generated_Pod';

my $result_metapod_fn = "$lib_dir/DBIx/Class2/Manual/ResultClass.pod";

die "POD generator must be executed from the dist root\n"
  unless -d $lib_dir and -d $pod_dir;

require File::Copy;
File::Copy::copy(
  "$result_metapod_fn.proto",
  "$result_metapod_fn",
) or die "Copying ResultClass proto pod ($result_metapod_fn) failed: $!";

# cleanup
END {
  local ($@, $!, $?);
  unlink $result_metapod_fn;
}

require Pod::Inherit;

Pod::Inherit->new({
   input_files       => $lib_dir,
   out_dir           => "$pod_dir/lib",
   force_permissions => 1,
   class_map         => {
      "DBIx::Class2::Relationship::HasMany"    => "DBIx::Class2::Relationship",
      "DBIx::Class2::Relationship::HasOne"     => "DBIx::Class2::Relationship",
      "DBIx::Class2::Relationship::BelongsTo"  => "DBIx::Class2::Relationship",
      "DBIx::Class2::Relationship::ManyToMany" => "DBIx::Class2::Relationship",
      "DBIx::Class2::ResultSourceProxy"        => "DBIx::Class2::ResultSource",
   },
   # skip the deprecated classes that give out *DEPRECATED* warnings
   skip_classes      => [ qw(
      lib/DBIx/Class2/Storage/DBI/Sybase/MSSQL.pm
      lib/DBIx/Class2/Serialize/Storable.pm
      lib/DBIx/Class2/ResultSetManager.pm
      lib/DBIx/Class2/InflateColumn/File.pm
      lib/DBIx/Class2/DB.pm
      lib/DBIx/Class2/CDBICompat/
      lib/DBIx/Class2/CDBICompat.pm
   ),
   # skip the ::Storage:: family for now
   qw(
      lib/DBIx/Class2/Storage/
      lib/DBIx/Class2/Storage.pm
   ),
      'lib/DBIx/Class2/Storage/DBI/Replicated/Pool.pm',  # this one just errors out with: The 'add_attribute' method cannot be called on an immutable instance
      'lib/DBIx/Class2/Relationship.pm',                 # it already documents its own inheritors
      'lib/DBIx/Class2/Core.pm',                         # we actually don't want this populated in favor of redirecting users to the ResultClass docs
      'lib/DBIx/Class2/Optional/Dependencies.pm'         # the POD is already auto-generated
   ],
   # these appear everywhere, and are typically lower-level methods not used by the general user
   skip_inherits     => [ qw/
      DBIx::Class2
      DBIx::Class2::Componentised
      Class::C3::Componentised
      DBIx::Class2::AccessorGroup
      Class::Accessor::Grouped
      Moose::Object
      Exporter
   / ],
   force_inherits    => {
      'DBIx::Class2::Manual::ResultClass' => 'DBIx::Class2::Core',  # this forces the contents of ::Core to be dumped into the POD doc for ::ResultClass
   },
   dead_links        => '',
   method_format     => 'L<%m|%c/%m>',
   #debug => 1,
})->write_pod;

# important - write_pod returns undef >.<
1;
